### PR TITLE
Issue #31 TrelloUI created

### PR DESCRIPTION
**Pull request by ParikshithMohan**
Trello UI created. Snapshot added (1-pk-31-trelloui.png)

### CODE REVIEW

**Comment by ParikshithMohan** [comment]
1-pk-31-trelloui

**Comment by azureus89** [comment]
a) work on the typography please, dont use raleway / display fonts for everything
b) need to see list and cards
c) are they done as components if not, ping here when list and card example is done will show you how to component-ise
d) add close button for the cards
e) is it custom css or skeleton framework?

**Comment by ParikshithMohan** [comment]
REFERENCE WEBSITE:
image

**Comment by ParikshithMohan** [comment]
MINE:
2-pk-31-trelloui

**Comment by ParikshithMohan** [comment]
@azureus89 ??

**Comment by azureus89** [comment]
Not replied yet because you need to do a) typography work ... front end work is ALWAYS about attention to details ... do you like how all the fonts and icons are looking ... do you honestly like it, do you think the spacing, padding, alignments are perfect, the weight and sizes ...  compared to the trello reference, you tell me yourself ... if you think they both look equally polished, thats a different issue we need to tackle ... if you dont think they look equally polished then you need to stop doing half assed work when updating a pull request ... if youre just commit and pushing to remote then work can be in any state, even on issue thread, its fine most times, but on a pull request every time you update a pull request it means you think you're done, and you're not

b) is done and is fine
c) will get activated once you've finished a) and b) .. and we will get into a call and componentise the elements
a) is not done

perhaps instead of rushing and doing half assed work and then badgering me, you can take your time and methodically pay attention to small details instead before you update this pull request

**Comment by ParikshithMohan** [comment]
3-pk-31-trelloui

**Comment by azureus89** [comment]
much better, +1 looks bad, TRLO_Sample1 is not vertically aligned right ... but okay, pass it this time ... lets move to componentising ... only passing it because we are getting late, but otherwise attention to detail means all details, thats where the challenge and pain in front end tasks are, without it you can finish designs very fast ... 

will co-ordinate on discord for timing on componentisation

**Comment by ParikshithMohan** [comment]
Don't know how to create vertical lines using border though.

**Comment by ParikshithMohan** [comment]
image

**Pull request merged**
