### PR TITLE
Vk 16 websocet doc

### PR DESCRIPTION
**Pull request by VikramShawFL**

### CODE REVIEW

**Comment by azureus89** [comment]
@VikramShawFL cant merge this branch, its unmaintained, 12 commits behind master

**Comment by VikramShawFL** [comment]
I can directly merge the doc file to master

**Comment by azureus89** [comment]
even so, only one confllict - its that port assignment line ... just one line - resolve conflict and commit updated branch so i can accept pull request

**Comment by azureus89** [comment]
> I can directly merge the doc file to master

no please don't do that ... resolve the conflict on this branch

**Comment by VikramShawFL** [comment]
Have resolved the conflict.

**Pull request merged**
