### PR TITLE
Bs 35 migration

### PR DESCRIPTION
**Pull request by sahabaishakhi**

### CODE REVIEW

**Comment by azureus89** [comment]
@sahabaishakhi Issue addressed?
Need to see screenshots / snapshots as well, upload here, and in snapshots folder

**Comment by sahabaishakhi** [comment]
Screenshot from 2019-10-11 12-31-14

**Comment by azureus89** [comment]
@sahabaishakhi the styles look off .. @ParikshithMohan please help review this and figure out whats different between the clj and cljs versions

**Comment by sahabaishakhi** [comment]
Screenshot from 2019-10-11 19-50-23
@azureus89 this is the screenshot of the ui rendered using the `trello-ui.clj` file.
The newer commit is because I had not change the name of trello-ui in handler.clj.

**Comment by sahabaishakhi** [comment]
@azureus89 @ParikshithMohan the UI for trello rendered using reagent appears to me to be the same as the clj one

**Comment by ParikshithMohan** [comment]
> Screenshot from 2019-10-11 19-50-23
> @azureus89 this is the screenshot of the ui rendered using the `trello-ui.clj` file.
> The newer commit is because I had not change the name of trello-ui in handler.clj.

you mean trelloUI.clj right..?
image

It has to look like this.

**Comment by azureus89** [comment]
> @azureus89 @ParikshithMohan the UI for trello rendered using reagent appears to me to be the same as the clj one

not at all ... front end work is about attention to detail .. i see a lot of discrepancies ... look closer

**Comment by azureus89** [comment]
find out whats wrong ... why the discrepancy ... @ParikshithMohan are you sure thats the latest render from clj?

**Comment by sahabaishakhi** [comment]
@ParikshithMohan `trello-ui` is the name of the function that I changed, from `trello_ui` that renders the code from `trelloui.clj` file (name changed from trelloUI.clj because clojure sometimes has issues with capital letters in names of files). I made a mistake by mentioning earlier that trello-ui is the file name. 
Note that I have replaced all of the underscores with dashes from all functions in both handler.clj and `trelloui.css`. 
What are the differences you can find see clearly between both the screenshots?
I can spot that the font is more bold in mine and the top right corner having `PM`inside the circle has lesser of a margin.

**Comment by ParikshithMohan** [comment]
> find out whats wrong ... why the discrepancy ... @ParikshithMohan are you sure thats the latest render from clj?

updated the comment

**Comment by sahabaishakhi** [comment]
> @azureus89 @ParikshithMohan the UI for trello rendered using reagent appears to me to be the same as the clj one

this was with reference to the trello page I can seen from the clj file in my system. could it depend on the browser being used? I'm using chrome

**Comment by azureus89** [comment]
> Screenshot from 2019-10-11 19-50-23
> @azureus89 this is the screenshot of the ui rendered using the `trello-ui.clj` file.
> The newer commit is because I had not change the name of trello-ui in handler.clj.

this is misleading ... i don't appreciate you sharing a screenshot of the clj version without indicating clearly as such ... because I thought it was a cljs render ... which is what this pull requset is clearly about ... this PR /  issue has nothing to do with how it looks on the clj render ... that problem has already been solved

**Comment by sahabaishakhi** [comment]
I sent screenshots of both the clj and the cljs renders. updated the cljs render in the snapshots folder and posted the above screenshot of it. the second one is the clj render.
There are two screenshots I've posted on this thread. first one is that of the cljs render and 2nd one is of the clj.

**Comment by azureus89** [comment]
lol then communication could be better ... cause that was very confusing ... its a good idea to add comment, timestamp etc when you're sharing images ... now i get what youre saying ..

**Comment by sahabaishakhi** [comment]
> I can spot that the font is more bold in mine and the top right corner having `PM`inside the circle has lesser of a margin.

EDIT: lesser padding
@ParikshithMohan can you check out my branch to see if the css rendering is happening correctly like how you want the UI to be? there seem to be some differences. but also both my clj and cljs screenshots look the same so could it be that my browser is taking different default fonts?

**Comment by ParikshithMohan** [comment]
> @ParikshithMohan `trello-ui` is the name of the function that I changed, from `trello_ui` that renders the code from `trelloui.clj` file (name changed from trelloUI.clj because clojure sometimes has issues with capital letters in names of files). I made a mistake by mentioning earlier that trello-ui is the file name.
> Note that I have replaced all of the underscores with dashes from all functions in both handler.clj and `trelloui.css`.
> What are the differences you can find see clearly between both the screenshots?
> I can spot that the font is more bold in mine and the top right corner having `PM`inside the circle has lesser of a margin.

1. All the buttons on top are longer than the margin
2. Searchbar is not right
3. All buttons are longer 
4. 'Add another list' not aligned
5. 'Add another card' not aligned
6. Expand button next to team1 not aligned
7. +1 not bold enough
8. team member names are not aligned
9.scrollbar on the right should be hidden

**Comment by sahabaishakhi** [comment]
@ParikshithMohan I see all of the differences now too. helps to have both the clj and cljs rendered versions on side by side tabs. except the can't tell difference between +1 boldness. I also noticed that the fonts used on the top most bar belong to different font families. 
EDIT: I see the font families being same that is sans-serif.

**Comment by ParikshithMohan** [comment]
@sahabaishakhi I branched out from urs. The UI looks good to me. Maybe its the resolution on ur laptop that is causing the problem. Is it 1366x768?

**Comment by ParikshithMohan** [comment]
@sahabaishakhi  I noticed that the head function is missing in the trelloui.cljs file. Did you do that on purpose?

This one, which is present in the clj file....

```
(defn head []
  [:head (include-css "css/trelloui.css" "css/skeleton.css" "css/normalize.css")
   [:title "TRELLO-UI"]
   [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
   [:link {:href "https://fonts.googleapis.com/css?family=Lato&display=swap" :rel "stylesheet"}]])
```

**Comment by azureus89** [comment]
ignore all previous comments on this issue ... this has become over complicated

**Comment by azureus89** [comment]
there is no cljs version right now .. you guys have diagnosed this and organised this completely wrong ... i am closing this pull request, because it is truly a mess, and moving back to the issue thread

**Comment by ParikshithMohan** [comment]
@sahabaishakhi @kattakavya How are you running the cljs file? I started the cljs repl(figwheel-main) and tried to go to the trelloui page, but it does not show up anything. As of now the trelloui page seems to be only running out of the clj file.

**Pull request closed without merging**
