### PR TITLE
Pk 6 boilerplate dash html

### PR DESCRIPTION
**Pull request by ParikshithMohan**
Dashboard done using html.

### CODE REVIEW

**Comment by azureus89** [comment]
Why HTML? Why not cljs?

**Comment by ParikshithMohan** [comment]
There is a problem with the repl.Its not starting up. So i did it using html.

**Comment by azureus89** [comment]
You need to create an issue then about the problem. You need to show me that this was the only wya to close the issue and something else was going wrong outside your jurisdiction .. otherwise I won't know why you took the decisions you took .. you need to justify your decision .. blame whatever is going wrong .. please do that

**Comment by ParikshithMohan** [comment]
can it be closed?

**Pull request merged**
