### PR TITLE
Pk 38 discordui

### PR DESCRIPTION
**Pull request by ParikshithMohan**
**DiscordUI**
Pulling request anyway. Don' know how to do componentization the right way. Need review to understand better.

### CODE REVIEW

**Comment by azureus89** [comment]
Okay 
And you're not pulling request .. you're submitting a pull request .. you are requesting me to pull your branch into master

**Comment by azureus89** [comment]
remove core.clj in your branch when you submit the next commit

**Comment by ParikshithMohan** [comment]
Lol.realized that after sending.ok will delete.

**Comment by ParikshithMohan** [comment]
image

**Comment by azureus89** [comment]
looks good, will review code tonight and pull into master if all good.
This is 20 credits + 10 if componentisation is good.

**Comment by azureus89** [comment]
@ParikshithMohan status on improvements discussed in last call ... also no record of what improvements were discussed, this is why better to run everything through issue / PR comments not just on call ...

**Comment by ParikshithMohan** [comment]
we discussed about changing the chat message from github message to direct message...and also implement using an if condition....still working on it...some problem with the repl..no error

**Comment by azureus89** [comment]
there will be an error, check messages, fundamental buffers ... and describe the behaviour
clj repl right?

**Comment by ParikshithMohan** [comment]
I only have a static solution for this problem.I don't know how to check when a new message is added. so now im just checking if the host name is 'Github' or not...based on that ill create the message.The problem is that i dont know how to make it work if another chat data structure is added.

**Comment by ParikshithMohan** [comment]
image

**Comment by azureus89** [comment]
Let me review the code and then we can close this

**Comment by azureus89** [comment]
write hiccup/clj documentation to help noobs like @sammed14 along .. speed up, dont rely completely on your call for knowledge transfer ... don't assume you'll always be there on call to help the person who wants to make some edits ... add documentation / comments and make it clear, while sammed works on responsive, and when thats done ill show you the chat handler part

**Comment by azureus89** [comment]
@ParikshithMohan conflicts with master
if related to config change, please work with @sahabaishakhi to resolve

**Comment by azureus89** [comment]
@ParikshithMohan conflicts not resolved ... need urgently

**Pull request merged**
