### PR TITLE
Simple documentation of metrics required, for humans

### PR DESCRIPTION
**Pull request by azureus89**

### CODE REVIEW

**Comment by azureus89** [comment]
@ParikshithMohan work with @Mazumda to find out from the metrics listed here, which are priority - make them bold

**Comment by azureus89** [comment]
@ParikshithMohan you can do that before merging PR into your branch

**Comment by Mazumda** [comment]
Metrics :


Metrics on top of game play data need to give an insight about the team. The opiniated end points are essentially guided by how a team 

- Thinks ( Strategizes) 
- Executes 
- Reacts 
- Arrives at Decisions 
- Collaborates
- Feels while working with each other

One factor of measuring all of the above is time. Time taken to Strategize, time taken to execute, time taken to change plans / react to new things etc. Time taken to decide and so on. The proxy element for each of the above is as follows

-  Thinks : Time to arrive at the decisions required by the team lead. Time spent deciding  .The time to decide is arbitrary. Team leads have the freedom to take their time, the clock starts ticking from round 1, there is a separate clock for the module in each round and a clock meant for a specific module, this allows us to see time across decision making independent of round, within the round and within each module

- Executes - This is time to complete a round, waiting time of teams, utilization percentages

- React : In this case it is a measure of time between original and changed strategies, am thinking the score board and chosen strategies should be available to all teams, and teams can copy a teams strategy for upto 2 times, am assuming teams will tend to copy the leading teams strategy, it will provide a proxy to evaluate how a team reacts. 

- Decision  making time - this is the time taken to take decisions, this can be within a time out, time between a time out request vs time taken to grant the same by the team lead, 

For collaboration and Feeling . The metrics will be driven by
Communication metrics - here we ned to find short cuts, emojis and kudos could be an option, frequency of message interchange, voting frequency and patterns using tapping etc, these metrics will be influenced by UI hacks that serve as proxy.

Survey data This is qualitative feedback around feelings,

**Comment by azureus89** [comment]
@Mazumda everything is timestampped, so we can derive time metrics as a view - ive got you covered on this -- also why we are moving to datomic where time is more native to the database itself

im leaving the explicit strategy parts as TBD for now
have finalised the metrics needed for now - split broadly as i see into two categories
a) actions of players during gameplay
b) metadata of player / team / sessions

find revised and compacted documentation in https://github.com/224-1/xtnt-micro/blob/pk-46-ktne/doc/forge/ktne/design-principles.org

**Pull request merged**
