### PR TITLE
Pk newsfeedui 17

### PR DESCRIPTION
**Pull request by ParikshithMohan**
Current UI look in snapshots: pk-17-newsfeedui-1-v2 & pk-17-newsfeedui-2-v2.

### CODE REVIEW

**Comment by azureus89** [comment]
@ParikshithMohan a) your branch is way behind master again and there is one conflict. Why does this keep happening?
b) avoid v2/v3 in file names, not necessary. put a timestamp instead if youre trying to show progress use the format yyyymmddhh-branch.png (hh is hour in 24 hour format)
so 2019090215-pk-17-newsfeedui.png

If you're only showing the final and not interested in showing progress, overwrite the files, and have only one file, no v2/v3.

**Comment by ParikshithMohan** [comment]
conflict fixed

**Comment by ParikshithMohan** [comment]
review and feedback pls.

**Comment by ParikshithMohan** [comment]
UI improved but not abled to push.Problem with magit.

**Comment by ParikshithMohan** [comment]
Most of the UI elements tweaked a little. Snapshots added. Need feedback on the font used though.

**Comment by ParikshithMohan** [comment]
is the layout ok?

**Comment by ParikshithMohan** [comment]
1-2019090415-pk-17-newsfeedui
2-2019090415-pk-17-newsfeedui

**Comment by azureus89** [comment]
good stuff, definitely better, but right hand side still too busy with all the bold, see how twitter makes it work. Continue till tomorrow, will pull final tomorrow and assign you to new tasks.

**Comment by ParikshithMohan** [comment]
Final update...?

1-2019090615-pk-17-newsfeedui
2-2019090615-pk-17-newsfeedui

**Comment by azureus89** [comment]
final update would be the end of the day :D

**Comment by ParikshithMohan** [comment]
?

**Pull request merged**
