### PR TITLE
Modified cljs-implementation doc

### PR DESCRIPTION
**Pull request by VikramShawFL**

### CODE REVIEW

**Comment by azureus89** [comment]
@kattakavya please clarify if the documentation in vikrams branch has made the issue clear for you, any gaps in the documentation please point out. You will need to review all of vikrams commits regarding documentation on this branch.
@VikramShawFL this PR will be accepeted once kavya has certified

**Comment by kattakavya** [comment]
@VikramShawFL I did not understood how the cljs-out gets created under resources, can you please provide the explanation for the below lines:
(the trickly part is the path to the ClojureScript bootstrap file. 
The default output path is available at cljs-out/[build-id]-main.js. )

**Comment by VikramShawFL** [comment]
> @VikramShawFL I did not understood how the cljs-out gets created under resources, can you please provide the explanation for the below lines:
> (the trickly part is the path to the ClojureScript bootstrap file.
> The default output path is available at cljs-out/[build-id]-main.js. )

@kattakavya Where I have the written that cljs-out will gets created under resource folder. Please read the modified doc once fully then you will have a brief idea about how you can implement the cljs figwheel-main in your project
image

**Comment by kattakavya** [comment]
@VikramShawFL 1.You have written after running cider-jack-in-cljs , cljs-out folder will be in xtnt-micro/target/public/cljs-out/ but in project it has given as  
image it is directing to the resource ,in target we have classes and stale.so confused were should we directory to?

2.I found in project.clj --> profiles both figwheel and rebel-readline-clj versions are same ,I dont think so both are same.
image

**Comment by VikramShawFL** [comment]
1)I was just following the earlier convention.
image
Since it is getting you confuse so you can change that ``resource`` to ``target``.  In target folder you will have only 2 folder initially, but once you start the ``cider -jack-in-cljs`` it will compile the cljs code to javascript code and create the public folder in target folder.

2)The dependency version keeps on changing, so you have to keep update your dependencies by going to different dependencies site from time to time.

**Comment by azureus89** [comment]
@VikramShawFL @kattakavya changing to target instead of resources folder is a good idea 👍 
I didn't realise this is why lein clean was not working, while trying to fix baishakhis issue, thought it was some linux problem.

**Comment by VikramShawFL** [comment]
> @VikramShawFL @kattakavya changing to target instead of resources folder is a good idea 👍
> I didn't realise this is why lein clean was not working, while trying to fix baishakhis issue, thought it was some linux problem.

No, the thing is target folder doesn't gets upload in the remote repository. so when you are cloning the repository from github even though you run ``lein run`` you have to run ``cider-jack-in-cljs`` to compile the cljs code. Then only you will able to see the websocket page

**Comment by azureus89** [comment]
thats good thats how it should be

**Comment by azureus89** [comment]
github isn't meant for easily exchanging executable files, its meant for code, anything that youre not directly coding on / required for coding, unnecessary to keep tracking and pushing ... thats why you use the .gitignore file .... target folder is automatically included in that ... anything in .gitignore doesnt get pushed ... for instance in all my projects i have notes and todos that you wont see because i put their path in the .gitignore file ... so when somebody else wants to run this, yes they need to compile clojurescript code first ... its a better way to do it .. lighter and neater, less error prone

**Comment by azureus89** [comment]
@VikramShawFL confirm no further additions for now, I will merge this

**Comment by VikramShawFL** [comment]
Yes, no further addition for now.

**Pull request merged**
