### PR TITLE
Issue #6 Dashboard created

### PR DESCRIPTION
**Pull request by ParikshithMohan**

### CODE REVIEW

**Comment by azureus89** [comment]
You haven't not synced with master in a long time it looks like. You are completely out of sync with master - 6 commits behind.
Please sync and resolve conflicts, i cant merge yet.

**Comment by ParikshithMohan** [comment]
I don't know how to solve this...resolve conflicts is not clickable

**Comment by ParikshithMohan** [comment]
its done on pk-6-boilerplate-dash-html branch.

https://github.com/224-1/xtnt-micro/blob/pk-6-boilerplate-dash-html/snapshot/pk-6-boilerplate-dash.PNG

**Comment by azureus89** [comment]
right conflicts because its pushed onto core.clj ... resolve this later, trello issues are priority

**Comment by ParikshithMohan** [comment]
ok

**Comment by azureus89** [comment]
@ParikshithMohan at some point when youre free resolve this conflict

**Comment by azureus89** [comment]
closing this, its never going to happen, we will re-do when the time comes, using updated knowledge / skills .. this is now redundant

**Pull request closed without merging**
