### PR TITLE
Multiple Builds Config Update

### PR DESCRIPTION
**Pull request by azureus89**
Integrate new config / project structure into master

### CODE REVIEW

**Review by sahabaishakhi — DISMISSED** [review]

**Comment by azureus89** [comment]
need to do:
1) lein clean to remove all files from target
2) check all routes in handler - '/', '/newsfeed','/trelloui'
3) the routes / and /trelloui should give a js file not found error in dev console on the browser
4) run the dev build ... compile ... test the '/' route, and check if all working
5) then run the trlo build ... compile ... test the '/trelloui' route and check if this and the '/' route continue to work

report any errors.

lesson for the future - do lein clean after core config changes, and start all over again. (Not required if only adding new project dependencies)

**Comment by azureus89** [comment]
a small clarification on test process: when doing the build you need to check in two ways:
1. figwheel should open the appropriate html host page for chat and trello projects - and the page should render what is expected
2. after builds runs and compiles, the relevant route in localhost:8000 also should start working with no errors

**Comment by sahabaishakhi** [comment]
> 2\. check all routes in handler - /, /newsfeed, trelloui
should this be checked after running lein run followed by checking localhost:8000?

**Comment by azureus89** [comment]
@sahabaishakhi yes sorry
after lein clean
do lein run .. and check on localhost all the routes
you should get errors on the cljs related routes (/ and /trelloui)

**Comment by sahabaishakhi** [comment]
@azureus89 I am getting errors on the chrome console on both the routes / and /trelloui. 
Screenshot from 2019-10-16 15-07-29
Screenshot from 2019-10-16 15-07-21

**Comment by sahabaishakhi** [comment]
after running the :dev build, I could see the appropriate chat page on both localhost:9500 and localhost:8000 
Screenshot from 2019-10-16 15-10-59
Screenshot from 2019-10-16 15-11-11

and upon running the :trlo build I could see the changes as well
Screenshot from 2019-10-16 15-15-28
Screenshot from 2019-10-16 15-15-32

**Review by sahabaishakhi — APPROVED** [review]

**Comment by azureus89** [comment]
@ParikshithMohan @kattakavya please test and review

**Comment by azureus89** [comment]
ASAP, so we can move this forward

**Comment by kattakavya** [comment]
@azureus89 @sahabaishakhi I have tested and reviewed, it was directed to the trelloui- page. Fine from my side.
image

**Comment by sahabaishakhi** [comment]
@kattakavya you haven't reviewed yet. you need to do so by approving it.

**Review by ParikshithMohan — APPROVED** [review]

**Review by kattakavya — APPROVED** [review]

**Pull request merged**
