### PR TITLE
Pk 46 ktne

### PR DESCRIPTION
**Pull request by ParikshithMohan**
part 2 docs added

### CODE REVIEW

**Comment by azureus89** [comment]
Approved .. let's move to module ideas

**Comment by azureus89** [comment]
Add module ideas based on this framework of what you want to get out of the game .. keep it simple .. lets aim to finalise three modules by tomorrow .. add all module ideas in a single file .. commit one module at a time

**Comment by azureus89** [comment]
@ParikshithMohan add module ideas in org files, and then I can close this issue when you've done 3 modules
@Mazumda module ideas from you - you can share in issue thread

**Comment by azureus89** [comment]
@ParikshithMohan yes to all 3 modules, will create new repo for dev work, and decide which to start with first, libraries etc ... merging and closing #46 
you can check with rupam and make the priority metrics bold in the new repo, we will have a copy of the document there as well

**Comment by Mazumda** [comment]
module ideas 

a modification of the "in the subject of keypad module" where the handler just communicates and the defuser clicks. 

step 1 - handler reads out 4, 6, or 8 symbols, gives sub sequence number
step 2 - defuser plugs in the sequence number and can pull up a 10X10, 14X14  matrix
step 3 - defuser needs to click all the occurrences of the symbols provided, mistakes will count as strikes
step 3 - defuser needs to click on final submit, scoring will depend on number of slides left out

**Comment by Mazumda** [comment]
modification of wires

instead of cutting wires we need to see it as fixing a  destroyed circuit. the module opens with a bunch of points on two sides and a set of wires that may be connected or disconnected or may not have wires at all . we need the manual to represent a target state, and the defuser to guide the handler how to reach the target state. the module will be asynchronous and all info can be passed in one shot, there will be sequence numbers for each point.

the handler can join a cut wire, join an existing cut wire or add a wire connection to 2 new points. 
while joinng the wire the handler may need to use different colored magnetic tape in the more complex variants.

**Comment by azureus89** [comment]
@Mazumda this discussion is in issue thread since pull request is now closed (changes have been accepted)

**Comment by azureus89** [comment]
@Mazumda mentioned on thread -- this issue is closed in this repo ... next discussion is in new issue, in new repo meant for developing modules, starting from tomorrow
current issue has been resolved, 3 modules chosen, document in place

**Pull request merged**
