### PR TITLE
Vk 4 websocket

### PR DESCRIPTION
**Pull request by VikramShawFL**
Added the documentation for clojurescript, figwheel, reagent / reframe to existing clojure project #12.
1) lein run: work
2) from emacs: cider-jack-in and cider-jack-in-cljs both working

### CODE REVIEW

**Comment by azureus89** [comment]
why change to markdown from org? markdown is inferior

**Comment by VikramShawFL** [comment]
The snippets which I added to explain the steps was not showing up. Only the sentences can be seen not the snippets that's why

**Review by azureus89 — COMMENTED** [review]
Have you tested that this works?
What does System/getenv PORT reference?

**Review by azureus89 — COMMENTED** [review]
on the clientside websocket will still try to connect to only 9500 ... what do you want to do about that?

**Review by azureus89 — COMMENTED** [review]
Why are you adding environment variables, without knowing how to manage them, no file to configure them, and not checking whether it breaks any existing code (like the cljs side websocket).

**Comment by VikramShawFL** [comment]
Upon running lein run the server starts at port 8000. On running cljs cider it automatically opens port 9500

**Comment by azureus89** [comment]
> The snippets which I added to explain the steps was not showing up. Only the sentences can be seen not the snippets that's why

Because your syntax was wrong.
https://orgmode.org/manual/Structure-of-code-blocks.html

**Comment by azureus89** [comment]
> Upon running lein run the server starts at port 8000. On running cljs cider it automatically opens port 9500

But the websocket is on port 8000 as per your code, therefore this wont work / is bound to crash.

2) What if the port assigned from system env is different, your websocket is still trying to connect to either 9500 or 8000 ... shouldn't that also connect to the same port assigned in the env variables.

**Comment by VikramShawFL** [comment]
Oh!! I wrote #+begin_clojure instead of #+BEGIN_SRC

> Because your syntax was wrong.
> https://orgmode.org/manual/Structure-of-code-blocks.html

**Comment by azureus89** [comment]
Most importantly, if you decided to use environment variables ... you need to provide a way to manage it ... this is unnecessary complication right now, clearly there are things you dont know in this part of the program, id appreciate if you told me that you didnt know what to do there, and to close this issue for now with 9500 hard coded, and to create a separate issue where we tackle environment variables - which are crucial and necessary for many things, including database connections etc.

Please revert to org mode documentation, and port assigned directly (:port 9500) ... make sure the client side is referencing the same port, test and submit commits and update on pull request when ready to merge.

**Comment by VikramShawFL** [comment]
Okay.

**Comment by azureus89** [comment]
impatience to close issues is a value :)
I will always try to get maximum done in every issue, you should try to get minimum done to finish the job as defined.

Optional port assignment / env variables were not part of issue definition, so you need to push back, thats your job, not my job -- i will always point out what else id like done.

**Comment by VikramShawFL** [comment]
It's because I'm getting this error with the websocket now after moving to figwheel-main where I'm sending the messages but it is not showing in the chat box

**Comment by azureus89** [comment]
> It's because I'm getting this error with the websocket now after moving to figwheel-main where I'm sending the messages but it is not showing in the chat box

this is because you have assigned the websocket port as 8000
whereas the cljs file is trying to connect to 9500

its not got anything to do with figwheel main
What i pushed yesterday is working fine
the only change you've made is the optional port assignment

**Comment by azureus89** [comment]
> > Upon running lein run the server starts at port 8000. On running cljs cider it automatically opens port 9500
> 
> But the websocket is on port 8000 as per your code, therefore this wont work / is bound to crash.
> 
> 1. What if the port assigned from system env is different, your websocket is still trying to connect to either 9500 or 8000 ... shouldn't that also connect to the same port assigned in the env variables.

This is what i was talking about ... the websocket is bound to fail, it is trying to connect to 9500 but you've moved the port to 8000 by default ... i fail to understand why you did that, there is no reason to change the default port.

**Comment by VikramShawFL** [comment]
But you told that the best way is to make the server also run on optional port because of that I made that changes

**Comment by azureus89** [comment]
> ver also run on optional port because of that I made that changes

Yes, but clearly you're not well versed with env variables etc ... so just tell me that, so that you can close the issue. It is the best way to do it, but most probably, you copy pasted it without understanding it - which doesn't help. So my job is to always ask you to do it in the best way possible, your job is to close the issue fast - if what im asking will take time, and is not REQUIRED to close the issue, you should tell me.

You can even ask for the issue to be changed and made smaller to close it fast. The goal for you is to close it fast, with as little effort as possible, not keep on stretching it.

**Comment by VikramShawFL** [comment]
Okay

**Comment by azureus89** [comment]
update here when confirmed tested and safe to merge

**Comment by VikramShawFL** [comment]
Yes, it is safe to merge

**Comment by azureus89** [comment]
@ParikshithMohan @kattakavya please note ... the master branch is now up to date with #20 fixed ... please port your front end code to this project on the relevant new / existing branch for your issues on this project

**Pull request merged**
